logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG


eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST:localhost}:${EUREKA_PORT:8761}/eureka/