server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 20
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.departmentservice.kafka.serialization.ObjectSerializer

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.transaction: TRACE

employee:
  service:
    url: http://localhost:8081