spring:
  datasource:
    url: jdbc:postgresql://department-service-db:5432/${POSTGRES_DB}
  kafka:
    producer:
      bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:${EUREKA_PORT:8761}/eureka/