services:
  department-service:
    build:
      context: ../department-service
      dockerfile: Dockerfile
    ports:
      - 9080:${DEPARTMENT_SERVICE_PORT}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env

  employee-service:
    build:
      context: ../employee-service
      dockerfile: Dockerfile
    ports:
      - 9081:${EMPLOYEE_SERVICE_PORT}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env

  notification-service:
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    ports:
      - 9082:${NOTIFICATION_SERVICE_PORT}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env

  department-service-db:
    image: postgres:latest
    container_name: department-service-db
    ports:
      - ${DEPARTMENT_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - department_service_data:/var/lib/postgresql/data

  employee-service-db:
    image: postgres:latest
    container_name: employee-service-db
    ports:
      - ${EMPLOYEE_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - employee_service_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - ${ZOOKEEPER_PORT}:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_PORT}:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://${HOST}:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  department_service_data:
  employee_service_data:
