services:
  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - ${EUREKA_PORT}:${EUREKA_PORT}
    networks:
      - test-network
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:${EUREKA_PORT}/eureka/
    networks:
      - test-network
    depends_on:
      - eureka-server
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
  department-service:
    build:
      context: ../department-service
      dockerfile: Dockerfile
    container_name: department-service
    networks:
      - test-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:${EUREKA_PORT}/eureka/
    env_file:
      - .env
    depends_on:
      - eureka-server
      - department-service-db

  employee-service:
    build:
      context: ../employee-service
      dockerfile: Dockerfile
    container_name: employee-service
    networks:
      - test-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:${EUREKA_PORT}/eureka/
    env_file:
      - .env
    depends_on:
      - eureka-server
      - employee-service-db

  notification-service:
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    networks:
      - test-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:${EUREKA_PORT}/eureka/
    env_file:
      - .env
    depends_on:
      - eureka-server
      - kafka

  department-service-db:
    image: postgres:latest
    container_name: department-service-db
    ports:
      - ${DEPARTMENT_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - test-network
    volumes:
      - department_service_data:/var/lib/postgresql/data

  employee-service-db:
    image: postgres:latest
    container_name: employee-service-db
    ports:
      - ${EMPLOYEE_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - test-network
    volumes:
      - employee_service_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - test-network
    ports:
      - ${ZOOKEEPER_PORT}:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_PORT}:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://${HOST}:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - test-network

volumes:
  department_service_data:
  employee_service_data:

networks:
  test-network:
    driver: bridge
