server:
  port: ${EMPLOYEE_SERVICE_PORT:8081}
  error:
    include-stacktrace: never
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 20
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:${EMPLOYEE_POSTGRES_PORT:5433}/${POSTGRES_DB:testdb}
    username: ${POSTGRES_USER:testuser}
    password: ${POSTGRES_PASS:testpass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  kafka:
    producer:
      bootstrap-servers: ${HOST:localhost}:${KAFKA_PORT:29092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.employeeservice.kafka.serialization.ObjectSerializer

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.transaction: TRACE

department:
  service:
    url: http://${HOST:localhost}:${DEPARTMENT_SERVICE_PORT:8080}