server:
  port: 0
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: employee-service
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 20
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:${EMPLOYEE_POSTGRES_PORT:5433}/${POSTGRES_DB:testdb}
    username: ${POSTGRES_USER:testuser}
    password: ${POSTGRES_PASS:testpass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/master-changelog.xml
  kafka:
    producer:
      bootstrap-servers: ${HOST:localhost}:${KAFKA_PORT:29092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.employeeservice.kafka.serialization.ObjectSerializer

kafka:
  topics:
    employeeCreate: employee-create-topic
    employeeUpdate: employee-update-topic
    employeeDelete: employee-delete-topic
    phoneCreate: phone-create-topic
    phoneUpdate: phone-update-topic
    phoneDelete: phone-delete-topic

department:
  service:
    url: ""

openapi:
  service:
    title: Employee Service API
    version: 1.0.0
    url: http://localhost:8080/api/v1/employee-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html