logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.transaction: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST:localhost}:${EUREKA_PORT:8761}/eureka/